curl -X POST http://localhost:3500/permisos/aprobar/recursos-humanos \
  -H "Content-Type: application/json" \
  -d '{
        "idPermiso": 1,
        "nuevoEstado": "RECURSOS HUMANOS APROBÓ"
      }'
