curl -X POST http://localhost:3500/solicitar-permiso \
  -H "Content-Type: application/json" \
  -d '{
        "idUsuario": 10,
        "permiso": "Vacaciones",
        "observaciones": "Tomar una semana de vacaciones",
        "fecha": "2024-03-14",
        "tipoPermiso": "COMPENSA",
        "fechaCompensacion": "2024-03-21",
        "compense": true
      }'
