curl -X POST http://localhost:3500/registro \
  -H "Content-Type: application/json" \
  -d '{
        "correo": "ejemplo@example.com",
        "clave": "contraseña123",
        "confirmarClave": "contraseña123",
        "cedula": "123456784",
        "nombre": "Juan",
        "apellidos": "Pérez",
        "telefono": "1234567890",
        "direccion": "Calle Principal",
        "lider": 1
      }'
